# Generated by Django 2.2.16 on 2021-12-08 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211018_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=1, validators=[django.core.validators.MaxValueValidator(10, 'Оценка не может быть более 10.'), django.core.validators.MinValueValidator(1, 'Оценка не может быть менее 1.')], verbose_name='Оценка произведения'),
        ),
    ]
